package com.prilepskiy.core.domain.model

import com.prilepskiy.core.data.apiService.response.productResponse.MealInfoResponse
import com.prilepskiy.core.data.databaseService.entity.MealInfoEntity


data class MealInfoModel (
    val dateModified: String,
    val idMeal: Int,
    val strArea: String,
    val strCategory: String,
    val strCreativeCommonsConfirmed: String,
    val strDrinkAlternate: String,
    val strImageSource: String,
    val strIngredient1: String,
    val strIngredient2: String,
    val strIngredient3: String,
    val strIngredient4: String,
    val strIngredient5: String,
    val strIngredient6: String,
    val strInstructions: String,
    val strMeal: String,
    val strMealThumb: String,
    val strMeasure1: String,
    val strMeasure10: String,
    val strMeasure11: String,
    val strMeasure12: String,
    val strMeasure13: String,
    val strMeasure14: String,
    val strMeasure15: String,
    val strMeasure16: String,
    val strMeasure17: String,
    val strMeasure18: String,
    val strMeasure19: String,
    val strMeasure2: String,
    val strMeasure20: String,
    val strMeasure3: String,
    val strMeasure4: String,
    val strMeasure5: String,
    val strMeasure6: String,
    val strMeasure7: String,
    val strMeasure8: String,
    val strMeasure9: String,
    val strSource: String,
    val strTags: String,
    val strYoutube: String
    )
{
    companion object{
        fun from(data: MealInfoResponse): MealInfoModel = with(data) {
            MealInfoModel(
                dateModified?:"",
                idMeal,
                strArea?:"",
                strCategory?:"",
                strCreativeCommonsConfirmed?:"",
                strDrinkAlternate?:"",
                strImageSource?:"",
                strIngredient1?:"",
                strIngredient2?:"",
                strIngredient3?:"",
                strIngredient4?:"",
                strIngredient5?:"",
                strIngredient6?:"",
                strInstructions,
                strMeal?:"",
                strMealThumb?:"",
                strMeasure1?:"",
                strMeasure10?:"",
                strMeasure11?:"",
                strMeasure12?:"",
                strMeasure13?:"",
                strMeasure14?:"",
                strMeasure15?:"",
                strMeasure16?:"",
                strMeasure17?:"",
                strMeasure18?:"",
                strMeasure19?:"",
                strMeasure2?:"",
                strMeasure20?:"",
                strMeasure3?:"",
                strMeasure4?:"",
                strMeasure5?:"",
                strMeasure6?:"",
                strMeasure7?:"",
                strMeasure8?:"",
                strMeasure9?:"",
                strSource?:"",
                strTags?:"",
                strYoutube?:""
            )
        }
        fun from(data: MealInfoEntity): MealInfoModel = with(data) {
            MealInfoModel(
                dateModified,
                idMeal,
                strArea,
                strCategory,
                strCreativeCommonsConfirmed,
                strDrinkAlternate,
                strImageSource,
                strIngredient1,
                strIngredient2,
                strIngredient3,
                strIngredient4,
                strIngredient5,
                strIngredient6,
                strInstructions,
                strMeal,
                strMealThumb,
                strMeasure1,
                strMeasure10,
                strMeasure11,
                strMeasure12,
                strMeasure13,
                strMeasure14,
                strMeasure15,
                strMeasure16,
                strMeasure17,
                strMeasure18,
                strMeasure19,
                strMeasure2,
                strMeasure20,
                strMeasure3,
                strMeasure4,
                strMeasure5,
                strMeasure6,
                strMeasure7,
                strMeasure8,
                strMeasure9,
                strSource,
                strTags,
                strYoutube
            )
        }
    }
}